apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-config
  namespace: laura-blog
data:
  BLOG_TITLE: "the Blog of Laura"
  BLOG_SUBTITLE: "Mes aventures GitOps"
  AUTHOR: "Laura"
  VERSION: "1.0.0"
  THEME: "dark"